### ISSUE TITLE
Extend Sweetests to Exercise Update Holon Descriptor

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-descriptors2#10]
Take the set of Holon Descriptors we're already creating and define a set of updates:

- update the details of each scalar property type (e.g., min_value, max_value for integer, is_fuzzy for boolean)
- add a property to a holon descriptor
- remove a property from a holon descriptor
- add a property to a composite descriptor
- remove a property from a composite descriptor

In case, do a get_holon_descriptor and ensure the update was, in fact, reflected.

**Comment by dauphin3** [comment]
I noticed that for unsigned integers, the min_value should be 0, so I reflected that in the functions
